[package]
name = "frdm-k64f"
version = "0.1.0"
authors = ["Miguel Pérez García <miguelpg_95@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k64f_hal = { path = "../k64_hal", version = "0.1.0"}